<a href="https://colab.research.google.com/github/Abhi10699/google-colab-playground/blob/main/customer_purchase_prediction_knn_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
!wget https://raw.githubusercontent.com/futurexskill/projects/main/knn-classification/purchase_history.csv

--2023-11-26 16:41:11--  https://raw.githubusercontent.com/futurexskill/projects/main/knn-classification/purchase_history.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30007 (29K) [text/plain]
Saving to: ‘purchase_history.csv’

purchase_history.cs 100%[===================>]  29.30K  --.-KB/s    in 0.001s  

2023-11-26 16:41:11 (28.0 MB/s) - ‘purchase_history.csv’ saved [30007/30007]



In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [13]:
df = pd.read_csv("purchase_history.csv")
df.head()

Customer ID  Gender  Age  Salary Product ID  Price  Purchased
0            1  Female   49   61000        P01   2000          1
1            2    Male   36   30000        P02   2000          1
2            3  Female   26   81000        P02   3500          1
3            4  Female   32   74000        P01   7000          0
4            5  Female   42   56000        P01   5000          0

In [14]:
df.shape

(1000, 7)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Customer ID  1000 non-null   int64 
 1   Gender       1000 non-null   object
 2   Age          1000 non-null   int64 
 3   Salary       1000 non-null   int64 
 4   Product ID   1000 non-null   object
 5   Price        1000 non-null   int64 
 6   Purchased    1000 non-null   int64 
dtypes: int64(5), object(2)
memory usage: 54.8+ KB


In [16]:
df.describe()

Customer ID          Age         Salary        Price    Purchased
count  1000.000000  1000.000000    1000.000000  1000.000000  1000.000000
mean    500.500000    40.989000   58667.000000  4435.500000     0.414000
std     288.819436    13.738837   23615.372044  1847.973148     0.492795
min       1.000000    18.000000   20000.000000  2000.000000     0.000000
25%     250.750000    29.000000   38000.000000  3500.000000     0.000000
50%     500.500000    40.000000   59000.000000  5000.000000     0.000000
75%     750.250000    53.000000   80000.000000  7000.000000     1.000000
max    1000.000000    64.000000  100000.000000  7000.000000     1.000000

In [18]:
gender_encoded = pd.get_dummies(df['Gender'])

In [19]:
gender_encoded

Female  Male
0         1     0
1         0     1
2         1     0
3         1     0
4         1     0
..      ...   ...
995       0     1
996       0     1
997       1     0
998       0     1
999       1     0

[1000 rows x 2 columns]

In [20]:
gender_encoded = pd.get_dummies(df['Gender'], drop_first=True)

In [21]:
gender_encoded

Male
0       0
1       1
2       0
3       0
4       0
..    ...
995     1
996     1
997     0
998     1
999     0

[1000 rows x 1 columns]

In [22]:
df = pd.concat([df, gender_encoded], axis=1)
df

Customer ID  Gender  Age  Salary Product ID  Price  Purchased  Male
0              1  Female   49   61000        P01   2000          1     0
1              2    Male   36   30000        P02   2000          1     1
2              3  Female   26   81000        P02   3500          1     0
3              4  Female   32   74000        P01   7000          0     0
4              5  Female   42   56000        P01   5000          0     0
..           ...     ...  ...     ...        ...    ...        ...   ...
995          996    Male   21   73000        P02   5000          1     1
996          997    Male   62   54000        P01   5000          0     1
997          998  Female   41   20000        P03   2000          0     0
998          999    Male   22   29000        P03   5000          0     1
999         1000  Female   49   36000        P03   3500          0     0

[1000 rows x 8 columns]

In [23]:
x = df[['Male','Age','Salary','Price']].to_numpy()
x

array([[    0,    49, 61000,  2000],
       [    1,    36, 30000,  2000],
       [    0,    26, 81000,  3500],
       ...,
       [    0,    41, 20000,  2000],
       [    1,    22, 29000,  5000],
       [    0,    49, 36000,  3500]])

In [26]:
y = df['Purchased'].to_numpy()
y

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [29]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((800, 4), (200, 4), (800,), (200,))

In [30]:
from sklearn.preprocessing import StandardScaler

In [31]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [32]:
x_train[:10]

array([[ 1.08347268, -1.09076887, -1.30749141,  0.30934614],
       [ 1.08347268,  0.97668947, -1.60377078,  1.39955279],
       [-0.92295821,  0.0906359 , -1.56144515,  0.30934614],
       [ 1.08347268, -0.27855309, -1.56144515,  0.30934614],
       [-0.92295821,  0.53366268,  0.68181289, -0.50830885],
       [ 1.08347268, -1.68147125, -0.24935083, -0.50830885],
       [-0.92295821, -0.42622869, -1.34981704, -1.32596384],
       [-0.92295821,  0.0167981 , -0.58795582,  0.30934614],
       [ 1.08347268,  1.49355405,  0.38553352, -0.50830885],
       [ 1.08347268, -1.16460666, -0.41865332,  1.39955279]])

In [36]:
from sklearn.neighbors import KNeighborsClassifier

K = 5
knn = KNeighborsClassifier(n_neighbors=5)

In [37]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [38]:
y_pred = knn.predict(x_test)

In [39]:
y_pred

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0])

In [41]:
from sklearn.metrics import accuracy_score

In [42]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.765

In [43]:
import pickle

# save scaler

with open("knn_model.pickle", 'wb') as f:
  pickle.dump(knn, f)
  f.close()

with open("knn_scaler.pickle", 'wb') as f:
  pickle.dump(scaler, f)
  f.close()